### ISSUE TITLE
Gear Icon Does Nothing

### ISSUE THREAD

**Issue by hoffmabc** [duosearch/openbazaar.chat#1]
I'm assuming this will open up a control panel or something that gives users some control over their profile on the site. Right now it's just non-functional.

![image](https://cloud.githubusercontent.com/assets/45482/25279851/d8e702f4-2675-11e7-957a-192d66a1fddd.png)

**Comment by jackkleeman** [comment]
You are correct, yes we will probably have some settings there soon

**Comment by JustinDrake** [comment]
We will put stuff related to the identity (PeerID, login/logout, etc.) there shortly

**Comment by JustinDrake** [comment]
Ok, the gear icon does something now. It shows the peer id and allows you to add it to the clipboard.

![screen shot 2017-04-24 at 14 59 35](https://cloud.githubusercontent.com/assets/731743/25340773/aab27dba-28fe-11e7-8e96-9ca610ffae7b.png)

**Comment by JustinDrake** [comment]
Ok, I've added the email, password (generated randomly for now), and a logout facility. An account is uniquely determined by the email-password combination.

At some point in the future I will add login and password change facilities.

![screen shot 2017-04-24 at 15 44 43](https://cloud.githubusercontent.com/assets/731743/25342832/1eca8c8c-2905-11e7-829d-95eecb621476.png)

**Comment by JustinDrake** [comment]
It's official, we have full login capabilities! Reuse your email-password combination on any device and it will automatically sync, 100% backed up and encrypted.

![screen shot 2017-04-24 at 17 37 47](https://cloud.githubusercontent.com/assets/731743/25348039/cf775524-2914-11e7-8c2a-035fb16c5471.png)
