### ISSUE TITLE
Trivial XSS in chat box

### ISSUE THREAD

**Issue by pierce403** [duosearch/openbazaar.chat#6]
It looks like you can just send anyone something like

<script>window.location='https://www.youtube.com/watch?v=dQw4w9WgXcQ'</script>

And point them at Rick Astley.

Of course you could also worm it out and flood the network, or take coins if this code were to run in a context where bitcoins could be reached.

**Comment by jackkleeman** [comment]
Wow, exceptionally good point. @JustinDrake this is probably a fairly urgent fix

**Comment by JustinDrake** [comment]
Known issue, thanks :)

**Comment by JustinDrake** [comment]
This should now be fixed. This issue was known to me and simultaneously reported by another security researcher on Slack a few minutes before you. I still want to give you a token reward of $5 to say thanks. Please send over an Ethereum address to collect the bounty.

**Comment by pierce403** [comment]
Neat, thanks.  You can use 0x68D7b67c71FAa3C557FDdBd28BbEee98a22946BD

**Comment by JustinDrake** [comment]
Sent, thanks 👍
